### ISSUE TITLE
Breakdown 'Invalid Chain Generation Clearly Planned' Milestone

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#510]

**Comment by mhuesch** [comment]
- [x] Read [qsm-in-depth](http://www.well-typed.com/blog/2019/01/qsm-in-depth/) in depth
- [x] Read [integrated-shrinking](http://www.well-typed.com/blog/2019/05/integrated-shrinking/) in depth
- [ ] Understand
  - [x] Hedgehog state machine (https://teh.id.au/posts/2017/07/15/state-machine-testing/index.html)
  - [x] references (in hedgehog)
  - [x] fuzzing (it's roughly analogous to what we're doing)
  - [x] HasTrace (typeclass in `cardano-ledger-specs`)
  - [x] shrinking of chains generated by HasTrace (and how references may be preserved)
  - [x] grok how goblins were applied to STS Signals in prior WIP. Figure out how to map that mechanic 
onto HasTrace.
    - [ ] Wire up an end to end run of goblins generation (library to BreedingPit to `goblins-test` executable) [very close!]
   - [ ] Figure our MonadGen monad transformer stack issues with hedgehog-1.0 [very stuck]
    - [ ] how `moo` drives the goblins to mutate `Trace`s
- [ ] First actions (after reading)
  - [x] Modify BreedingPit to fit with the new STSs
  - [ ] Apply Goblins to STS DBLOCK (simpler since it only contains delegation info)

**Comment by mhuesch** [comment]
Good progress today! Built on yesterday’s work and got a demo set up end to end (goblins library, to breeding pit, to goblins-test executable). The only thing omitted were MonadGen instances for Monad transformer stacks using Hedgehog’s GenT. That type changed in 1.0 and now it’s involves crazy MonadTrans and MonadTransJuggle instances which I do not understand yet. So the code is in place, and the approach seems to work, but I haven’t been able to do test runs because of the MonadGen issue. 

On Monday I’ll keep going with MonadTrans weirdness.

**Comment by mhuesch** [comment]
I've closed this because I'm transferring the work over to new tickets which will be assigned to the currently open https://github.com/input-output-hk/cardano-ledger/milestone/14
